
- name: add nodejs repository key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: add nodejs repository
  copy: src=nodesource.list dest=/etc/apt/sources.list.d/nodesource.list

- name: install nodejs
  apt: name=apt-transport-https state=present

- name: install nodejs
  apt: name=nodejs update_cache=True state=present
