

- name: install `git`
  apt: name=git state=latest

- name: setup `nvm` repository
  git: repo=https://github.com/creationix/nvm dest=/opt/nvm

- name: create `node` directory
  file: path=/usr/local/node state=directory mode=0755

- name: setup `nvm` profile.d entry
  copy: src=nodejs.sh dest=/etc/profile.d/nodejs.sh owner=root group=root mode=0644

- name: install `nodejs`
  shell: . /etc/profile.d/nodejs.sh && nvm install 5.2.0

- name: set default `nodejs` version to `5.2.0`
  shell: . /etc/profile.d/nodejs.sh && nvm alias default 5.2.0
