
- name: install `git`
  apt: name=git state=latest

- name: setup `ws2811` repository
  git: repo=https://github.com/izaakschroeder/ws2811 dest=/opt/ws2811

- name: install node_modules
  npm: path=/opt/ws2811

- name: install systemd service
  copy: src=ws2811.service dest=/etc/systemd/system
  notify: reload systemd

- name: enable ws2811
  service: name=ws2811 enabled=yes state=started
